version: '2'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/dojo-on-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
