default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dojo-overwatch_development

test:
  <<: *default
  database: dojo-overwatch_test

production:
  <<: *default
  database: dojo-overwatch_production
  username: dojo-overwatch
  password: <%= ENV['DOJO-OVERWATCH_DATABASE_PASSWORD'] %>
